output file:
processed_pytorch3dcorresponding_points_alignment304.json
function:
corresponding_points_alignment
Error Cases:
ERROR: file or directory not found: /local/data0/moved_data/pytorch3d/tests/test_points_allignment.py


Pass or Failed: 1

Related Failed Test Cases:
set()

All Test Cases On Generated code:
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/pytorch3d/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/Organized_benchmark
collecting ... collected 0 items

============================ no tests ran in 0.00s =============================


Final Test Result:
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/pytorch3d/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/Organized_benchmark
collecting ... collected 0 items

============================ no tests ran in 0.00s =============================


Initial Result:
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/pytorch3d/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/Organized_benchmark
collecting ... collected 0 items

============================ no tests ran in 0.00s =============================
