output file:
processed_nncfcreate_nncf_network60.json
function:
create_nncf_network
Error Cases:
2025-01-09 18:49:04.727238: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-01-09 18:49:04.738182: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-01-09 18:49:04.741535: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-09 18:49:04.750304: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
ERROR: found no collectors for /local/data0/moved_data/publishablew/nncf/nncf/tests/torch/sparsity/movement/test_algo.py::TestControllerCreation


Pass or Failed: 1

Related Failed Test Cases:
set()

All Test Cases On Generated code:
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, tensorflow, onnx
============================= test session starts ==============================
platform linux -- Python 3.9.0, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/nncf/nncf/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/nncf/nncf/tests/torch
configfile: pytest.ini
plugins: mock-3.14.0, dependency-0.6.0
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
_______________ ERROR collecting sparsity/movement/test_algo.py ________________
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1778: in _get_module
    return importlib.import_module("." + module_name, self.__name__)
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:790: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py:28: in <module>
    from ...modeling_utils import PreTrainedModel
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/modeling_utils.py:48: in <module>
    from .loss.loss_utils import LOSS_MAPPING
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/loss/loss_utils.py:19: in <module>
    from .loss_deformable_detr import DeformableDetrForObjectDetectionLoss, DeformableDetrForSegmentationLoss
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/loss/loss_deformable_detr.py:4: in <module>
    from ..image_transforms import center_to_corners_format
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/image_transforms.py:50: in <module>
    import tensorflow as tf
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/__init__.py:47: in <module>
    from tensorflow._api.v2 import __internal__
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/__init__.py:8: in <module>
    from tensorflow._api.v2.__internal__ import autograph
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py:8: in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/autograph/core/ag_ctx.py:21: in <module>
    from tensorflow.python.autograph.utils import ag_logging
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/autograph/utils/__init__.py:17: in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/autograph/utils/context_managers.py:19: in <module>
    from tensorflow.python.framework import ops
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:5906: in <module>
    ) -> Optional[Callable[[Any], message.Message]]:
/usr/local/lib/python3.9/typing.py:243: in inner
    return func(*args, **kwds)
/usr/local/lib/python3.9/typing.py:316: in __getitem__
    return self._getitem(self, parameters)
/usr/local/lib/python3.9/typing.py:433: in Optional
    return Union[arg, type(None)]
/usr/local/lib/python3.9/typing.py:243: in inner
    return func(*args, **kwds)
/usr/local/lib/python3.9/typing.py:316: in __getitem__
    return self._getitem(self, parameters)
/usr/local/lib/python3.9/typing.py:421: in Union
    parameters = _remove_dups_flatten(parameters)
/usr/local/lib/python3.9/typing.py:215: in _remove_dups_flatten
    all_params = set(params)
E   TypeError: unhashable type: 'list'

The above exception was the direct cause of the following exception:
../publishablew/nncf/nncf/tests/torch/sparsity/movement/test_algo.py:43: in <module>
    from tests.torch.sparsity.movement.helpers import FACTOR_NAME_IN_MOVEMENT_STAT
../publishablew/nncf/nncf/tests/torch/sparsity/movement/helpers/__init__.py:13: in <module>
    from tests.torch.sparsity.movement.helpers.run_recipe import BaseMockRunRecipe
../publishablew/nncf/nncf/tests/torch/sparsity/movement/helpers/run_recipe.py:29: in <module>
    from transformers import CLIPVisionModel
<frozen importlib._bootstrap>:1055: in _handle_fromlist
    ???
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1767: in __getattr__
    value = getattr(module, name)
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1766: in __getattr__
    module = self._get_module(self._class_to_module[name])
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1780: in _get_module
    raise RuntimeError(
E   RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
E   unhashable type: 'list'
=========================== short test summary info ============================
ERROR ../publishablew/nncf/nncf/tests/torch/sparsity/movement/test_algo.py - ...
=============================== 1 error in 2.56s ===============================


Final Test Result:
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, tensorflow, onnx
============================= test session starts ==============================
platform linux -- Python 3.9.0, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/nncf/nncf/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/nncf/nncf/tests/torch
configfile: pytest.ini
plugins: mock-3.14.0, dependency-0.6.0
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
_______________ ERROR collecting sparsity/movement/test_algo.py ________________
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1778: in _get_module
    return importlib.import_module("." + module_name, self.__name__)
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:790: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py:28: in <module>
    from ...modeling_utils import PreTrainedModel
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/modeling_utils.py:48: in <module>
    from .loss.loss_utils import LOSS_MAPPING
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/loss/loss_utils.py:19: in <module>
    from .loss_deformable_detr import DeformableDetrForObjectDetectionLoss, DeformableDetrForSegmentationLoss
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/loss/loss_deformable_detr.py:4: in <module>
    from ..image_transforms import center_to_corners_format
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/image_transforms.py:50: in <module>
    import tensorflow as tf
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/__init__.py:47: in <module>
    from tensorflow._api.v2 import __internal__
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/__init__.py:8: in <module>
    from tensorflow._api.v2.__internal__ import autograph
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py:8: in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/autograph/core/ag_ctx.py:21: in <module>
    from tensorflow.python.autograph.utils import ag_logging
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/autograph/utils/__init__.py:17: in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/autograph/utils/context_managers.py:19: in <module>
    from tensorflow.python.framework import ops
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:5906: in <module>
    ) -> Optional[Callable[[Any], message.Message]]:
/usr/local/lib/python3.9/typing.py:243: in inner
    return func(*args, **kwds)
/usr/local/lib/python3.9/typing.py:316: in __getitem__
    return self._getitem(self, parameters)
/usr/local/lib/python3.9/typing.py:433: in Optional
    return Union[arg, type(None)]
/usr/local/lib/python3.9/typing.py:243: in inner
    return func(*args, **kwds)
/usr/local/lib/python3.9/typing.py:316: in __getitem__
    return self._getitem(self, parameters)
/usr/local/lib/python3.9/typing.py:421: in Union
    parameters = _remove_dups_flatten(parameters)
/usr/local/lib/python3.9/typing.py:215: in _remove_dups_flatten
    all_params = set(params)
E   TypeError: unhashable type: 'list'

The above exception was the direct cause of the following exception:
../publishablew/nncf/nncf/tests/torch/sparsity/movement/test_algo.py:43: in <module>
    from tests.torch.sparsity.movement.helpers import FACTOR_NAME_IN_MOVEMENT_STAT
../publishablew/nncf/nncf/tests/torch/sparsity/movement/helpers/__init__.py:13: in <module>
    from tests.torch.sparsity.movement.helpers.run_recipe import BaseMockRunRecipe
../publishablew/nncf/nncf/tests/torch/sparsity/movement/helpers/run_recipe.py:29: in <module>
    from transformers import CLIPVisionModel
<frozen importlib._bootstrap>:1055: in _handle_fromlist
    ???
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1767: in __getattr__
    value = getattr(module, name)
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1766: in __getattr__
    module = self._get_module(self._class_to_module[name])
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1780: in _get_module
    raise RuntimeError(
E   RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
E   unhashable type: 'list'
=========================== short test summary info ============================
ERROR ../publishablew/nncf/nncf/tests/torch/sparsity/movement/test_algo.py - ...
=============================== 1 error in 2.58s ===============================


Initial Result:
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, tensorflow, onnx
============================= test session starts ==============================
platform linux -- Python 3.9.0, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/nncf/nncf/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/nncf/nncf/tests/torch
configfile: pytest.ini
plugins: mock-3.14.0, dependency-0.6.0
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
_______________ ERROR collecting sparsity/movement/test_algo.py ________________
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1778: in _get_module
    return importlib.import_module("." + module_name, self.__name__)
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:790: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py:28: in <module>
    from ...modeling_utils import PreTrainedModel
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/modeling_utils.py:48: in <module>
    from .loss.loss_utils import LOSS_MAPPING
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/loss/loss_utils.py:19: in <module>
    from .loss_deformable_detr import DeformableDetrForObjectDetectionLoss, DeformableDetrForSegmentationLoss
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/loss/loss_deformable_detr.py:4: in <module>
    from ..image_transforms import center_to_corners_format
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/image_transforms.py:50: in <module>
    import tensorflow as tf
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/__init__.py:47: in <module>
    from tensorflow._api.v2 import __internal__
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/__init__.py:8: in <module>
    from tensorflow._api.v2.__internal__ import autograph
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py:8: in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/autograph/core/ag_ctx.py:21: in <module>
    from tensorflow.python.autograph.utils import ag_logging
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/autograph/utils/__init__.py:17: in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/autograph/utils/context_managers.py:19: in <module>
    from tensorflow.python.framework import ops
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:5906: in <module>
    ) -> Optional[Callable[[Any], message.Message]]:
/usr/local/lib/python3.9/typing.py:243: in inner
    return func(*args, **kwds)
/usr/local/lib/python3.9/typing.py:316: in __getitem__
    return self._getitem(self, parameters)
/usr/local/lib/python3.9/typing.py:433: in Optional
    return Union[arg, type(None)]
/usr/local/lib/python3.9/typing.py:243: in inner
    return func(*args, **kwds)
/usr/local/lib/python3.9/typing.py:316: in __getitem__
    return self._getitem(self, parameters)
/usr/local/lib/python3.9/typing.py:421: in Union
    parameters = _remove_dups_flatten(parameters)
/usr/local/lib/python3.9/typing.py:215: in _remove_dups_flatten
    all_params = set(params)
E   TypeError: unhashable type: 'list'

The above exception was the direct cause of the following exception:
../publishablew/nncf/nncf/tests/torch/sparsity/movement/test_algo.py:43: in <module>
    from tests.torch.sparsity.movement.helpers import FACTOR_NAME_IN_MOVEMENT_STAT
../publishablew/nncf/nncf/tests/torch/sparsity/movement/helpers/__init__.py:13: in <module>
    from tests.torch.sparsity.movement.helpers.run_recipe import BaseMockRunRecipe
../publishablew/nncf/nncf/tests/torch/sparsity/movement/helpers/run_recipe.py:29: in <module>
    from transformers import CLIPVisionModel
<frozen importlib._bootstrap>:1055: in _handle_fromlist
    ???
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1767: in __getattr__
    value = getattr(module, name)
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1766: in __getattr__
    module = self._get_module(self._class_to_module[name])
../publishablew/nncf/nncf/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py:1780: in _get_module
    raise RuntimeError(
E   RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
E   unhashable type: 'list'
=========================== short test summary info ============================
ERROR ../publishablew/nncf/nncf/tests/torch/sparsity/movement/test_algo.py - ...
=============================== 1 error in 7.77s ===============================
